//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saina.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GridViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saina.WPF.Properties.GridViewResources", typeof(GridViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیلتر.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string DataForm_AddNew {
            get {
                return ResourceManager.GetString("DataForm_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string DataForm_BeginEdit {
            get {
                return ResourceManager.GetString("DataForm_BeginEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string DataForm_Delete {
            get {
                return ResourceManager.GetString("DataForm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا.
        /// </summary>
        public static string DataForm_MoveCurrentToFirst {
            get {
                return ResourceManager.GetString("DataForm_MoveCurrentToFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتها.
        /// </summary>
        public static string DataForm_MoveCurrentToLast {
            get {
                return ResourceManager.GetString("DataForm_MoveCurrentToLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        public static string DataForm_MoveCurrentToNext {
            get {
                return ResourceManager.GetString("DataForm_MoveCurrentToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی.
        /// </summary>
        public static string DataForm_MoveCurrentToPrevious {
            get {
                return ResourceManager.GetString("DataForm_MoveCurrentToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ را وارد نمایید.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و.
        /// </summary>
        public static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل.
        /// </summary>
        public static string FilterContains {
            get {
                return ResourceManager.GetString("FilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان با.
        /// </summary>
        public static string FilterEndsWith {
            get {
                return ResourceManager.GetString("FilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل در.
        /// </summary>
        public static string FilterIsContainedIn {
            get {
                return ResourceManager.GetString("FilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساوی باشد.
        /// </summary>
        public static string FilterIsEqualTo {
            get {
                return ResourceManager.GetString("FilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساوی است با.
        /// </summary>
        public static string FilterIsEqualTo1 {
            get {
                return ResourceManager.GetString("FilterIsEqualTo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگتر از.
        /// </summary>
        public static string FilterIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگتر یا مساوی.
        /// </summary>
        public static string FilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچکتر از.
        /// </summary>
        public static string FilterIsLessThan {
            get {
                return ResourceManager.GetString("FilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچکتر یا مساوی.
        /// </summary>
        public static string FilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نا برابر.
        /// </summary>
        public static string FilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار داشتن.
        /// </summary>
        public static string FilterIsNotNull {
            get {
                return ResourceManager.GetString("FilterIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی بودن.
        /// </summary>
        public static string FilterIsNull {
            get {
                return ResourceManager.GetString("FilterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساس به بزرگی حروف.
        /// </summary>
        public static string FilterMatchCase {
            get {
                return ResourceManager.GetString("FilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا.
        /// </summary>
        public static string FilterOr {
            get {
                return ResourceManager.GetString("FilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب همه.
        /// </summary>
        public static string FilterSelectAll {
            get {
                return ResourceManager.GetString("FilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب ردیف هایی با مقدار.
        /// </summary>
        public static string FilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("FilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شود با.
        /// </summary>
        public static string FilterStartsWith {
            get {
                return ResourceManager.GetString("FilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای اضافه کردن اینجا کلیک کنید.
        /// </summary>
        public static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن فیلتر.
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و.
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل.
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل نباشد.
        /// </summary>
        public static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام شود با.
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل در.
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهی باشد.
        /// </summary>
        public static string GridViewFilterIsEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساوی باشد.
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگتر از.
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگتر یا مساوی.
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچکتر از.
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچکتر یا مساوی.
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهی نباشد.
        /// </summary>
        public static string GridViewFilterIsNotEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساوی نباشد.
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی نباشد.
        /// </summary>
        public static string GridViewFilterIsNotNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی باشد.
        /// </summary>
        public static string GridViewFilterIsNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساس به بزرگی حروف.
        /// </summary>
        public static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا.
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب همه.
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب ردیف هایی با مقدار.
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شود با.
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک سرصفحه ستون را بکشید و آن را اینجا بگذارید تا بر اساس آن ستون گروه بندی شود.
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه.
        /// </summary>
        public static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بندی با :.
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped1 {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک سرصفحه ستون را بکشید و آن را اینجا بگذارید تا بر اساس آن ستون گروه بندی شود.
        /// </summary>
        public static string GroupPanelText {
            get {
                return ResourceManager.GetString("GroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه.
        /// </summary>
        public static string GroupPanelTopText {
            get {
                return ResourceManager.GetString("GroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بندی با :.
        /// </summary>
        public static string GroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string RadDataPagerOf {
            get {
                return ResourceManager.GetString("RadDataPagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string RadDataPagerPage {
            get {
                return ResourceManager.GetString("RadDataPagerPage", resourceCulture);
            }
        }
    }
}
