//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saina.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS Project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saina.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اسناد.
        /// </summary>
        internal static string accountdocuments {
            get {
                return ResourceManager.GetString("accountdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم حسابداری.
        /// </summary>
        internal static string accountingsetting {
            get {
                return ResourceManager.GetString("accountingsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب های بانکی.
        /// </summary>
        internal static string bankAccounts {
            get {
                return ResourceManager.GetString("bankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست بانک ها.
        /// </summary>
        internal static string banks {
            get {
                return ResourceManager.GetString("banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست شرکت ها.
        /// </summary>
        internal static string companies {
            get {
                return ResourceManager.GetString("companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شرکت.
        /// </summary>
        internal static string companysystem {
            get {
                return ResourceManager.GetString("companysystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست ارز.
        /// </summary>
        internal static string currencies {
            get {
                return ResourceManager.GetString("currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان.
        /// </summary>
        internal static string CustomerListView {
            get {
                return ResourceManager.GetString("CustomerListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش مشتریان.
        /// </summary>
        internal static string customersOrder {
            get {
                return ResourceManager.GetString("customersOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تفصیل.
        /// </summary>
        internal static string dls {
            get {
                return ResourceManager.GetString("dls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گذاری اسناد.
        /// </summary>
        internal static string documentnumberings {
            get {
                return ResourceManager.GetString("documentnumberings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ ارز.
        /// </summary>
        internal static string exchangeRates {
            get {
                return ResourceManager.GetString("exchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی.
        /// </summary>
        internal static string financialYears {
            get {
                return ResourceManager.GetString("financialYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم عمومی.
        /// </summary>
        internal static string generalsetting {
            get {
                return ResourceManager.GetString("generalsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب گروه.
        /// </summary>
        internal static string gLs {
            get {
                return ResourceManager.GetString("gLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی گروه.
        /// </summary>
        internal static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه ورود.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش.
        /// </summary>
        internal static string orderPrep {
            get {
                return ResourceManager.GetString("orderPrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پرسنل.
        /// </summary>
        internal static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم دریافت و پرداخت.
        /// </summary>
        internal static string receivepaymentsetting {
            get {
                return ResourceManager.GetString("receivepaymentsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم خرده فروشی.
        /// </summary>
        internal static string retailsetting {
            get {
                return ResourceManager.GetString("retailsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم حقوق و دستمزد.
        /// </summary>
        internal static string salarysetting {
            get {
                return ResourceManager.GetString("salarysetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم فروش.
        /// </summary>
        internal static string settingsale {
            get {
                return ResourceManager.GetString("settingsale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم بازرگانی خرید.
        /// </summary>
        internal static string shoppingsetting {
            get {
                return ResourceManager.GetString("shoppingsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب معین.
        /// </summary>
        internal static string sLs {
            get {
                return ResourceManager.GetString("sLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کل.
        /// </summary>
        internal static string tLs {
            get {
                return ResourceManager.GetString("tLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی کاربران.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
